export interface IngredientEntry {
  name: string;
  alias?: string;
  category: string;
}

export const INGREDIENT_DB: IngredientEntry[] = [
  // 🥩 Proteins
  { name: 'chicken breast', category: 'Proteins' },
  { name: 'chicken thigh', category: 'Proteins' },
  { name: 'ground chicken', category: 'Proteins' },
  { name: 'whole chicken', category: 'Proteins' },
  { name: 'ground beef', category: 'Proteins' },
  { name: 'beef steak', category: 'Proteins' },
  { name: 'beef stew meat', category: 'Proteins' },
  { name: 'beef roast', category: 'Proteins' },
  { name: 'beef short ribs', category: 'Proteins' },
  { name: 'pork chop', category: 'Proteins' },
  { name: 'pork tenderloin', category: 'Proteins' },
  { name: 'bacon', category: 'Proteins' },
  { name: 'ham', category: 'Proteins' },
  { name: 'ground pork', category: 'Proteins' },
  { name: 'pork belly', category: 'Proteins' },
  { name: 'lamb', category: 'Proteins' },
  { name: 'ground lamb', category: 'Proteins' },
  { name: 'turkey', category: 'Proteins' },
  { name: 'ground turkey', category: 'Proteins' },
  { name: 'turkey breast', category: 'Proteins' },
  { name: 'salmon', category: 'Proteins' },
  { name: 'tuna', category: 'Proteins' },
  { name: 'shrimp', category: 'Proteins' },
  { name: 'cod', category: 'Proteins' },
  { name: 'tilapia', category: 'Proteins' },
  { name: 'sardines', category: 'Proteins' },
  { name: 'crab', category: 'Proteins' },
  { name: 'lobster', category: 'Proteins' },
  { name: 'clams', category: 'Proteins' },
  { name: 'scallops', category: 'Proteins' },
  { name: 'mussels', category: 'Proteins' },
  { name: 'tofu', category: 'Proteins' },
  { name: 'tempeh', category: 'Proteins' },
  { name: 'edamame', category: 'Proteins' },
  { name: 'duck breast', category: 'Proteins' },
  { name: 'sausage', category: 'Proteins' },
  { name: 'pepperoni', category: 'Proteins' },
  { name: 'prosciutto', category: 'Proteins' },

  // 🥦 Vegetables
  { name: 'garlic', category: 'Vegetables' },
  { name: 'onion', category: 'Vegetables' },
  { name: 'red onion', category: 'Vegetables' },
  { name: 'shallot', category: 'Vegetables' },
  { name: 'green onion', category: 'Vegetables' },
  { name: 'scallion', alias: 'green onion', category: 'Vegetables' },
  { name: 'leek', category: 'Vegetables' },
  { name: 'bell pepper', category: 'Vegetables' },
  { name: 'red bell pepper', category: 'Vegetables' },
  { name: 'jalapeño', category: 'Vegetables' },
  { name: 'serrano pepper', category: 'Vegetables' },
  { name: 'tomato', category: 'Vegetables' },
  { name: 'cherry tomato', category: 'Vegetables' },
  { name: 'roma tomato', category: 'Vegetables' },
  { name: 'sun-dried tomato', category: 'Vegetables' },
  { name: 'carrot', category: 'Vegetables' },
  { name: 'celery', category: 'Vegetables' },
  { name: 'cucumber', category: 'Vegetables' },
  { name: 'zucchini', category: 'Vegetables' },
  { name: 'potato', category: 'Vegetables' },
  { name: 'sweet potato', category: 'Vegetables' },
  { name: 'russet potato', category: 'Vegetables' },
  { name: 'broccoli', category: 'Vegetables' },
  { name: 'cauliflower', category: 'Vegetables' },
  { name: 'spinach', category: 'Vegetables' },
  { name: 'baby spinach', category: 'Vegetables' },
  { name: 'kale', category: 'Vegetables' },
  { name: 'lettuce', category: 'Vegetables' },
  { name: 'romaine lettuce', category: 'Vegetables' },
  { name: 'arugula', category: 'Vegetables' },
  { name: 'cabbage', category: 'Vegetables' },
  { name: 'bok choy', category: 'Vegetables' },
  { name: 'napa cabbage', category: 'Vegetables' },
  { name: 'eggplant', category: 'Vegetables' },
  { name: 'asparagus', category: 'Vegetables' },
  { name: 'green beans', category: 'Vegetables' },
  { name: 'snap peas', category: 'Vegetables' },
  { name: 'peas', category: 'Vegetables' },
  { name: 'corn', category: 'Vegetables' },
  { name: 'avocado', category: 'Vegetables' },
  { name: 'artichoke', category: 'Vegetables' },
  { name: 'beet', category: 'Vegetables' },
  { name: 'radish', category: 'Vegetables' },
  { name: 'turnip', category: 'Vegetables' },
  { name: 'butternut squash', category: 'Vegetables' },
  { name: 'acorn squash', category: 'Vegetables' },
  { name: 'pumpkin', category: 'Vegetables' },
  { name: 'Brussels sprouts', category: 'Vegetables' },
  { name: 'fennel', category: 'Vegetables' },
  { name: 'watercress', category: 'Vegetables' },

  // 🍄 Mushrooms
  { name: 'button mushroom', category: 'Mushrooms' },
  { name: 'portobello mushroom', category: 'Mushrooms' },
  { name: 'shiitake mushroom', category: 'Mushrooms' },
  { name: 'oyster mushroom', category: 'Mushrooms' },
  { name: 'enoki mushroom', category: 'Mushrooms' },
  { name: 'cremini mushroom', category: 'Mushrooms' },
  { name: 'porcini mushroom', category: 'Mushrooms' },
  { name: 'wild mushroom', category: 'Mushrooms' },
  { name: 'mixed mushrooms', category: 'Mushrooms' },
  { name: 'maitake mushroom', category: 'Mushrooms' },
  { name: 'chestnut mushroom', category: 'Mushrooms' },
  { name: 'king oyster mushroom', category: 'Mushrooms' },
  { name: 'dried mushroom', category: 'Mushrooms' },

  // 🍎 Fruits
  { name: 'lemon', category: 'Fruits' },
  { name: 'lime', category: 'Fruits' },
  { name: 'orange', category: 'Fruits' },
  { name: 'grapefruit', category: 'Fruits' },
  { name: 'apple', category: 'Fruits' },
  { name: 'green apple', category: 'Fruits' },
  { name: 'banana', category: 'Fruits' },
  { name: 'mango', category: 'Fruits' },
  { name: 'pineapple', category: 'Fruits' },
  { name: 'strawberry', category: 'Fruits' },
  { name: 'blueberry', category: 'Fruits' },
  { name: 'raspberry', category: 'Fruits' },
  { name: 'blackberry', category: 'Fruits' },
  { name: 'grape', category: 'Fruits' },
  { name: 'peach', category: 'Fruits' },
  { name: 'nectarine', category: 'Fruits' },
  { name: 'pear', category: 'Fruits' },
  { name: 'plum', category: 'Fruits' },
  { name: 'kiwi', category: 'Fruits' },
  { name: 'watermelon', category: 'Fruits' },
  { name: 'cantaloupe', category: 'Fruits' },
  { name: 'coconut', category: 'Fruits' },
  { name: 'raisins', category: 'Fruits' },
  { name: 'dates', category: 'Fruits' },
  { name: 'dried cranberries', alias: 'craisins', category: 'Fruits' },
  { name: 'pomegranate', category: 'Fruits' },
  { name: 'papaya', category: 'Fruits' },
  { name: 'lychee', category: 'Fruits' },
  { name: 'passion fruit', category: 'Fruits' },
  { name: 'fig', category: 'Fruits' },

  // 🧀 Dairy & Eggs
  { name: 'egg', category: 'Dairy & Eggs' },
  { name: 'egg yolk', category: 'Dairy & Eggs' },
  { name: 'egg white', category: 'Dairy & Eggs' },
  { name: 'milk', category: 'Dairy & Eggs' },
  { name: 'whole milk', category: 'Dairy & Eggs' },
  { name: 'skim milk', category: 'Dairy & Eggs' },
  { name: 'butter', category: 'Dairy & Eggs' },
  { name: 'unsalted butter', category: 'Dairy & Eggs' },
  { name: 'heavy cream', category: 'Dairy & Eggs' },
  { name: 'whipping cream', alias: 'heavy cream', category: 'Dairy & Eggs' },
  { name: 'sour cream', category: 'Dairy & Eggs' },
  { name: 'cream cheese', category: 'Dairy & Eggs' },
  { name: 'cheddar cheese', category: 'Dairy & Eggs' },
  { name: 'mozzarella', category: 'Dairy & Eggs' },
  { name: 'parmesan', category: 'Dairy & Eggs' },
  { name: 'feta cheese', category: 'Dairy & Eggs' },
  { name: 'ricotta', category: 'Dairy & Eggs' },
  { name: 'gouda', category: 'Dairy & Eggs' },
  { name: 'brie', category: 'Dairy & Eggs' },
  { name: 'swiss cheese', category: 'Dairy & Eggs' },
  { name: 'gruyere', category: 'Dairy & Eggs' },
  { name: 'monterey jack', category: 'Dairy & Eggs' },
  { name: 'pepper jack', category: 'Dairy & Eggs' },
  { name: 'blue cheese', category: 'Dairy & Eggs' },
  { name: 'yogurt', category: 'Dairy & Eggs' },
  { name: 'greek yogurt', category: 'Dairy & Eggs' },
  { name: 'cottage cheese', category: 'Dairy & Eggs' },
  { name: 'half and half', category: 'Dairy & Eggs' },
  { name: 'condensed milk', category: 'Dairy & Eggs' },
  { name: 'evaporated milk', category: 'Dairy & Eggs' },
  { name: 'oat milk', category: 'Dairy & Eggs' },
  { name: 'almond milk', category: 'Dairy & Eggs' },
  { name: 'cream of tartar', category: 'Dairy & Eggs' },

  // 🫙 Pantry
  { name: 'flour', category: 'Pantry' },
  { name: 'all-purpose flour', alias: 'flour', category: 'Pantry' },
  { name: 'bread flour', category: 'Pantry' },
  { name: 'sugar', category: 'Pantry' },
  { name: 'brown sugar', category: 'Pantry' },
  { name: 'powdered sugar', category: 'Pantry' },
  { name: 'honey', category: 'Pantry' },
  { name: 'maple syrup', category: 'Pantry' },
  { name: 'agave', category: 'Pantry' },
  { name: 'baking soda', category: 'Pantry' },
  { name: 'baking powder', category: 'Pantry' },
  { name: 'vanilla extract', category: 'Pantry' },
  { name: 'cornstarch', category: 'Pantry' },
  { name: 'breadcrumbs', category: 'Pantry' },
  { name: 'panko breadcrumbs', category: 'Pantry' },
  { name: 'peanut butter', category: 'Pantry' },
  { name: 'almond butter', category: 'Pantry' },
  { name: 'tahini', category: 'Pantry' },
  { name: 'cocoa powder', category: 'Pantry' },
  { name: 'chocolate chips', category: 'Pantry' },
  { name: 'dark chocolate', category: 'Pantry' },
  { name: 'yeast', category: 'Pantry' },
  { name: 'almonds', category: 'Pantry' },
  { name: 'walnuts', category: 'Pantry' },
  { name: 'cashews', category: 'Pantry' },
  { name: 'pine nuts', category: 'Pantry' },
  { name: 'peanuts', category: 'Pantry' },
  { name: 'sunflower seeds', category: 'Pantry' },
  { name: 'sesame seeds', category: 'Pantry' },
  { name: 'flax seeds', category: 'Pantry' },
  { name: 'chia seeds', category: 'Pantry' },

  // 🌾 Grains & Pasta
  { name: 'white rice', category: 'Grains & Pasta' },
  { name: 'brown rice', category: 'Grains & Pasta' },
  { name: 'basmati rice', category: 'Grains & Pasta' },
  { name: 'jasmine rice', category: 'Grains & Pasta' },
  { name: 'rice', category: 'Grains & Pasta' },
  { name: 'spaghetti', category: 'Grains & Pasta' },
  { name: 'spaghetti noodles', alias: 'spaghetti', category: 'Grains & Pasta' },
  { name: 'penne', category: 'Grains & Pasta' },
  { name: 'fettuccine', category: 'Grains & Pasta' },
  { name: 'lasagna noodles', alias: 'lasagna', category: 'Grains & Pasta' },
  { name: 'ramen noodles', category: 'Grains & Pasta' },
  { name: 'instant ramen', alias: 'ramen noodles', category: 'Grains & Pasta' },
  { name: 'rice noodles', category: 'Grains & Pasta' },
  { name: 'udon noodles', category: 'Grains & Pasta' },
  { name: 'soba noodles', category: 'Grains & Pasta' },
  { name: 'egg noodles', category: 'Grains & Pasta' },
  { name: 'pasta', category: 'Grains & Pasta' },
  { name: 'rigatoni', category: 'Grains & Pasta' },
  { name: 'orzo', category: 'Grains & Pasta' },
  { name: 'rotini', category: 'Grains & Pasta' },
  { name: 'bread', category: 'Grains & Pasta' },
  { name: 'sourdough bread', alias: 'sourdough', category: 'Grains & Pasta' },
  { name: 'baguette', category: 'Grains & Pasta' },
  { name: 'tortilla', category: 'Grains & Pasta' },
  { name: 'flour tortilla', category: 'Grains & Pasta' },
  { name: 'corn tortilla', category: 'Grains & Pasta' },
  { name: 'pita bread', category: 'Grains & Pasta' },
  { name: 'naan', category: 'Grains & Pasta' },
  { name: 'oats', category: 'Grains & Pasta' },
  { name: 'rolled oats', alias: 'oats', category: 'Grains & Pasta' },
  { name: 'quinoa', category: 'Grains & Pasta' },
  { name: 'couscous', category: 'Grains & Pasta' },
  { name: 'barley', category: 'Grains & Pasta' },
  { name: 'polenta', category: 'Grains & Pasta' },

  // 🫒 Oils & Condiments
  { name: 'olive oil', category: 'Oils & Condiments' },
  { name: 'extra virgin olive oil', alias: 'olive oil', category: 'Oils & Condiments' },
  { name: 'vegetable oil', category: 'Oils & Condiments' },
  { name: 'canola oil', alias: 'vegetable oil', category: 'Oils & Condiments' },
  { name: 'sesame oil', category: 'Oils & Condiments' },
  { name: 'coconut oil', category: 'Oils & Condiments' },
  { name: 'avocado oil', category: 'Oils & Condiments' },
  { name: 'soy sauce', category: 'Oils & Condiments' },
  { name: 'low-sodium soy sauce', alias: 'soy sauce', category: 'Oils & Condiments' },
  { name: 'fish sauce', category: 'Oils & Condiments' },
  { name: 'oyster sauce', category: 'Oils & Condiments' },
  { name: 'hoisin sauce', category: 'Oils & Condiments' },
  { name: 'sriracha', category: 'Oils & Condiments' },
  { name: 'hot sauce', category: 'Oils & Condiments' },
  { name: 'worcestershire sauce', category: 'Oils & Condiments' },
  { name: 'balsamic vinegar', category: 'Oils & Condiments' },
  { name: 'rice wine vinegar', category: 'Oils & Condiments' },
  { name: 'apple cider vinegar', category: 'Oils & Condiments' },
  { name: 'white vinegar', category: 'Oils & Condiments' },
  { name: 'ketchup', category: 'Oils & Condiments' },
  { name: 'mustard', category: 'Oils & Condiments' },
  { name: 'dijon mustard', category: 'Oils & Condiments' },
  { name: 'mayonnaise', category: 'Oils & Condiments' },
  { name: 'teriyaki sauce', category: 'Oils & Condiments' },
  { name: 'miso paste', category: 'Oils & Condiments' },
  { name: 'BBQ sauce', category: 'Oils & Condiments' },
  { name: 'hot chili oil', category: 'Oils & Condiments' },
  { name: 'tahini', category: 'Oils & Condiments' },
  { name: 'ponzu sauce', category: 'Oils & Condiments' },

  // 🌶 Spices & Herbs
  { name: 'garlic powder', category: 'Spices & Herbs' },
  { name: 'onion powder', category: 'Spices & Herbs' },
  { name: 'cumin', category: 'Spices & Herbs' },
  { name: 'paprika', category: 'Spices & Herbs' },
  { name: 'smoked paprika', category: 'Spices & Herbs' },
  { name: 'chili powder', category: 'Spices & Herbs' },
  { name: 'oregano', category: 'Spices & Herbs' },
  { name: 'dried oregano', alias: 'oregano', category: 'Spices & Herbs' },
  { name: 'basil', category: 'Spices & Herbs' },
  { name: 'fresh basil', alias: 'basil', category: 'Spices & Herbs' },
  { name: 'thyme', category: 'Spices & Herbs' },
  { name: 'rosemary', category: 'Spices & Herbs' },
  { name: 'bay leaf', category: 'Spices & Herbs' },
  { name: 'cinnamon', category: 'Spices & Herbs' },
  { name: 'nutmeg', category: 'Spices & Herbs' },
  { name: 'turmeric', category: 'Spices & Herbs' },
  { name: 'fresh ginger', alias: 'ginger', category: 'Spices & Herbs' },
  { name: 'ginger', category: 'Spices & Herbs' },
  { name: 'ground ginger', alias: 'ginger', category: 'Spices & Herbs' },
  { name: 'curry powder', category: 'Spices & Herbs' },
  { name: 'garam masala', category: 'Spices & Herbs' },
  { name: 'cayenne pepper', category: 'Spices & Herbs' },
  { name: 'black pepper', category: 'Spices & Herbs' },
  { name: 'red pepper flakes', category: 'Spices & Herbs' },
  { name: 'parsley', category: 'Spices & Herbs' },
  { name: 'fresh parsley', alias: 'parsley', category: 'Spices & Herbs' },
  { name: 'cilantro', category: 'Spices & Herbs' },
  { name: 'dill', category: 'Spices & Herbs' },
  { name: 'mint', category: 'Spices & Herbs' },
  { name: 'chives', category: 'Spices & Herbs' },
  { name: 'coriander', category: 'Spices & Herbs' },
  { name: 'cardamom', category: 'Spices & Herbs' },
  { name: 'allspice', category: 'Spices & Herbs' },
  { name: 'cloves', category: 'Spices & Herbs' },
  { name: 'star anise', category: 'Spices & Herbs' },
  { name: 'five spice', category: 'Spices & Herbs' },
  { name: 'Italian seasoning', category: 'Spices & Herbs' },
  { name: 'za\'atar', category: 'Spices & Herbs' },
  { name: 'sumac', category: 'Spices & Herbs' },
  { name: 'sage', category: 'Spices & Herbs' },
  { name: 'tarragon', category: 'Spices & Herbs' },

  // 🥫 Canned & Packaged
  { name: 'canned tomatoes', category: 'Canned & Packaged' },
  { name: 'diced tomatoes', alias: 'canned tomatoes', category: 'Canned & Packaged' },
  { name: 'crushed tomatoes', alias: 'canned tomatoes', category: 'Canned & Packaged' },
  { name: 'tomato paste', category: 'Canned & Packaged' },
  { name: 'tomato sauce', category: 'Canned & Packaged' },
  { name: 'coconut milk', category: 'Canned & Packaged' },
  { name: 'chicken broth', category: 'Canned & Packaged' },
  { name: 'beef broth', category: 'Canned & Packaged' },
  { name: 'vegetable broth', category: 'Canned & Packaged' },
  { name: 'canned beans', category: 'Canned & Packaged' },
  { name: 'black beans', category: 'Canned & Packaged' },
  { name: 'chickpeas', category: 'Canned & Packaged' },
  { name: 'pinto beans', category: 'Canned & Packaged' },
  { name: 'kidney beans', category: 'Canned & Packaged' },
  { name: 'white beans', category: 'Canned & Packaged' },
  { name: 'canned corn', category: 'Canned & Packaged' },
  { name: 'canned tuna', category: 'Canned & Packaged' },
  { name: 'canned salmon', category: 'Canned & Packaged' },
  { name: 'lentils', category: 'Canned & Packaged' },
  { name: 'red lentils', alias: 'lentils', category: 'Canned & Packaged' },
  { name: 'instant ramen', category: 'Canned & Packaged' },
  { name: 'olives', category: 'Canned & Packaged' },
  { name: 'capers', category: 'Canned & Packaged' },
  { name: 'artichoke hearts', category: 'Canned & Packaged' },
  { name: 'roasted red peppers', category: 'Canned & Packaged' },
];

export const CATEGORY_META: { emoji: string; name: string }[] = [
  { emoji: '🥩', name: 'Proteins' },
  { emoji: '🥦', name: 'Vegetables' },
  { emoji: '🍄', name: 'Mushrooms' },
  { emoji: '🍎', name: 'Fruits' },
  { emoji: '🧀', name: 'Dairy & Eggs' },
  { emoji: '🫙', name: 'Pantry' },
  { emoji: '🌾', name: 'Grains & Pasta' },
  { emoji: '🫒', name: 'Oils & Condiments' },
  { emoji: '🌶', name: 'Spices & Herbs' },
  { emoji: '🥫', name: 'Canned & Packaged' },
];
